### ISSUE TITLE
Rename module and namespaces to include contact

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-derivative-contracts#6]
Currently name simply says derivatives, which would work if our application was a completely financial software which it is not. Name like "vc-module-contract-derivatives" would be a better choice. Same with a class names and namespaces: "Contacts.Derivatives", or "ContractDerivatives".

**Comment by asvishnyakov** [comment]
@Woland2k [DerivativeContracts](https://en.wikipedia.org/wiki/Derivative_(finance)#Common_derivative_contract) then
